default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "hintsly_development")  %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "hintsly_test")  %>

production:
  <<: *default
  username: Hintsly
  database: <%= ENV.fetch("DATABASE_NAME", "hintsly_production")  %>
